version: "3.7"

services:
  back_end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: phamthanhhuy/back-end:${BACK_END:-latest}
    ports:
      - "8888:8888"
    container_name: back-end-container
    networks:
      - deploy
    depends_on:
      - mysql-db

  fe-cms:
    build:
      context: ./fe-cms
      dockerfile: Dockerfile
    image: phamthanhhuy/fe-cms:${FE_CMS:-latest}
    ports:
      - "3000:3000"
    container_name: fe-cms
    networks:
      - deploy

  fe-store:
    build:
      context: ./fe-store
      dockerfile: Dockerfile
    image: phamthanhhuy/fe-store:${FE_STORE:-latest}
    ports:
      - "3001:3001"
    container_name: fe-store
    networks:
      - deploy

  mysql-db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fashion
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/fashion.sql:/docker-entrypoint-initdb.d/fashion.sql
    networks:
      - deploy
    depends_on:
      - minio-storage

  minio-storage:
    image: minio/minio:latest
    container_name: minio-container
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./fashion-cloud/fashion-cloud-minio:/data
    command: server /data --console-address ":9001"
    networks:
      - deploy

volumes:
  mysql-data:

networks:
  deploy:
